### ISSUE TITLE
Cannot set no default launcher (aka Android System)

### ISSUE THREAD

**Issue by xxx508** [Henry-ZHR/KillDomainVerification#6]
Hello. So, I was using this module and it is working for me (ex. youtube or telegram links), and also I somehow (maybe it was a bug, idk) managed to set no default launcher (in settings it was "Android System"). Recently, I rebooted my phone, and my system is now forcing me to set default launcher, even when I close the choice menu and don't click any of it or changing the state of "make default" checkbox. Clicking on Home button does nothing.
I ran "logcat -s KillDomainVerification" from termux and it printed nothing.
However, I can set no-default-launcher by clearing out defaults in settings of the app. But, it will set default after some time.
Specs: stock MIUI 14.0.8 (with Magisk and LsPosed), device is Redmi Note 12 4G (topaz)
Default Applications menu:
![Screenshot_2024-04-10-16-07-01-889_com.android.settings.jpg](https://github.com/Henry-ZHR/KillDomainVerification/assets/55109110/01e56a36-1e23-42eb-8c2a-6df96c8f9252)
How it needs to be when going home or clicking on home button while in the launcher:
![Screenshot_2024-04-10-16-10-31-494_android.jpg](https://github.com/Henry-ZHR/KillDomainVerification/assets/55109110/5ea30bdc-9413-4fe0-a59e-3cf9e2eedb12)

I will be more then happy if you give me an advice how to change it back to no default launcher, because I need them for different reasons (ex. running commands from t-ui, and searching apps visually from pixel launcher). Maybe, there is a file in the system that i can remove from changing (well, on stock ROM it's difficult)? Thanks.

**Comment by Henry-ZHR** [comment]
This module should only work for normal links, but not for "launcher".

Sorry but unsetting default launcher is not my need, and I won't spend time on it. You'd better ask someone else or investigate Android source code yourself.

**Comment by xxx508** [comment]
Hi there, it seems that I needed to bring back Play Store for some reason. It's working as I need now. Anyway, thanks for your work, it helps a lot.
