### ISSUE TITLE
does not allow "add link" to an app if same link is verified to a different app

### ISSUE THREAD

**Issue by Lanchon** [Henry-ZHR/KillDomainVerification#7]
hi,

thanks for the module!

in android 13, each app has verified links you cannot control and optional unverified links that you can choose to enable (plus the all-or-nothing setting for handling links).

turns out that you cannot add an unverified link to an app if another app has the same link as verified. the UI is disabled:

![image](https://github.com/Henry-ZHR/KillDomainVerification/assets/3977813/50f89de4-121d-4939-88ff-7ad86f962921)

this means that, although the link chooser pops up, the options you can enable are still artificially limited.

**Comment by Henry-ZHR** [comment]
Modifying "open by default" settings should have no effect when the module enabled.

Expected behavior: whatever settings, always show all options in popup when you click a link

**Comment by Lanchon** [comment]
ok, so no need to select the desired URLs for each app? it would have saved me time to know this lol

if that's true then please go ahead and close this issue.
